apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gofer-tls
  namespace: gofer
spec:
  secretName: gofer-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - gofer.weslab.vip
