apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gofer-data
  namespace: gofer
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 1Gi
